
spring:  profiles:
    active: qa




---
spring:
  profiles: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/employeecrud?useSSL=false
    password: root
  jpa:
    properties:
      hibernate:
        ddl-auto: update
      show-sql: true
welcome:
  message: Welcome to Daily Code Buffer!!!!
  
---
spring:
  profiles: qa
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/employeecrud-qa
    password: root
  jpa:
    properties:
      hibernate:
        ddl-auto: update
      show-sql: true
welcome:
  message: Welcome to Daily Code Buffer!!!!
  
---
spring:
  profiles: prod
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/employeecrud?useSSL=false
    password: root
  jpa:
    properties:
      hibernate:
        ddl-auto: update
      show-sql: true
welcome:
  message: Welcome to Daily Code Buffer!!!!